Do poszukiwania pierwiastków funkcji w Julii używamy pakietu Roots

In [1]:
using Roots  
using Plots

INFO: Initializing package repository /mnt/juliabox/.julia/v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl


In [17]:
# przykładowa funkcja do testów
f(x) = cos(x) - x
plot(f, -2, 2)

Funkcja <i> fzero</i>  dobiera odpowiedni algorytm w zależności od sposobu wywołania.


Metoda bisekcji - jesli wywołamy fzero z podaniem  przedziału (tutaj [0,1])

In [3]:
x = fzero(f, 0, 1, verbose=true)  

Results of univariate zero finding:

* Converged to: 0.7390851332151607
* Algorithm Roots.Bisection()
* iterations: 62
* function evaluations: 64
* stopped as x_n ≈ x_{n-1} using atol=xabstol, rtol=xreltol

Trace:
x_0 =  0.0000000000000000,	 f(x_0) =  1.0000000000000000
x_1 =  0.0000000000000000,	 f(x_1) =  1.0000000000000000
x_2 =  0.0000000000000000,	 f(x_2) =  1.0000000000000000
x_3 =  0.0000000000000000,	 f(x_3) =  1.0000000000000000
x_4 =  0.0000000000000000,	 f(x_4) =  1.0000000000000000
x_5 =  0.0000000002401066,	 f(x_5) =  0.9999999997598934
x_6 =  0.0000154972076416,	 f(x_6) =  0.9999845026722767
x_7 =  0.0039367675781250,	 f(x_7) =  0.9960554833624009
x_8 =  0.0627441406250000,	 f(x_8) =  0.9352880914742220
x_9 =  0.2504882812500000,	 f(x_9) =  0.7183032222476061
x_10 =  0.5004882812500000,	 f(x_10) =  0.3768600815324116
x_11 =  0.5004882812500000,	 f(x_11) =  0.3768600815324116
x_12 =  0.6253662109375000,	 f(x_12) =  0.1853825851723409
x_13 =  0.6878051757812500,	 f(x_13) = 

0.7390851332151607

Innym typem metody jest metoda Newtona, potrzebująca punktu startowego i wykorzystująca pochodną funkcji.

In [4]:
# metoda Newtona funkcja, punkt startowy (tutaj x0=0)
newton(f, 0, verbose=true)

Results of univariate zero finding:

* Converged to: 0.7390851332151607
* Algorithm Roots.Newton()
* iterations: 5
* function evaluations: 6
* stopped as |f(x_n)| ≤ max(δ, max(1,|x|)⋅ϵ) using δ = abstol, ϵ = reltol

Trace:
x_0 =  0.0000000000000000,	 f(x_0) =  1.0000000000000000
x_1 =  1.0000000000000000,	 f(x_1) = -0.4596976941318602
x_2 =  0.7503638678402439,	 f(x_2) = -0.0189230738221174
x_3 =  0.7391128909113617,	 f(x_3) = -0.0000464558989908
x_4 =  0.7390851333852840,	 f(x_4) = -0.0000000002847206
x_5 =  0.7390851332151607,	 f(x_5) =  0.0000000000000000



0.7390851332151607

Metoda Newtona korzysta z pakietu ForwardDiff, aby obliczyć pochodną funkcji. Pakiet ten udostępnia dla uzytkownika   operator D, który zwraca funkcję pochodną

In [5]:
# przykład użycia wprost :
# obliczamy wartości x^2 dla liczb 1..10
x=linspace(1,10,10)
y=(x->x^2).(x)

10-element Array{Float64,1}:
   1.0
   4.0
   9.0
  16.0
  25.0
  36.0
  49.0
  64.0
  81.0
 100.0

In [6]:
# obliczamy wartości funkcji pochodnej dla x^2 czyli 2x:
yprim=D(x->x^2).(x)

10-element Array{Float64,1}:
  2.0
  4.0
  6.0
  8.0
 10.0
 12.0
 14.0
 16.0
 18.0
 20.0

In [7]:
# można tez samemu podać pochodną
newton(f, D(f),0, verbose=true)

Results of univariate zero finding:

* Converged to: 0.7390851332151607
* Algorithm Roots.Newton()
* iterations: 5
* function evaluations: 6
* stopped as |f(x_n)| ≤ max(δ, max(1,|x|)⋅ϵ) using δ = abstol, ϵ = reltol

Trace:
x_0 =  0.0000000000000000,	 f(x_0) =  1.0000000000000000
x_1 =  1.0000000000000000,	 f(x_1) = -0.4596976941318602
x_2 =  0.7503638678402439,	 f(x_2) = -0.0189230738221174
x_3 =  0.7391128909113617,	 f(x_3) = -0.0000464558989908
x_4 =  0.7390851333852840,	 f(x_4) = -0.0000000002847206
x_5 =  0.7390851332151607,	 f(x_5) =  0.0000000000000000



0.7390851332151607

Metoda siecznych

In [8]:
# wywołanie fzero używając punktu startowego (a nie przedziału) oraz opcji order=1   wykorzystuje metodę siecznych  - #podajemy punkt startowy tutaj x0=0 oraz order=1
x = fzero(f, 0,order=1, verbose=true) 

Results of univariate zero finding:

* Converged to: 0.7390851332151607
* Algorithm Roots.Secant()
* iterations: 7
* function evaluations: 9
* stopped as |f(x_n)| ≤ max(δ, max(1,|x|)⋅ϵ) using δ = abstol, ϵ = reltol

Trace:
x_0 =  0.0100000000000000,	 f(x_0) =  0.9899500004166653
x_1 =  0.0000000000000000,	 f(x_1) =  1.0000000000000000
x_2 =  0.9950249168748567,	 f(x_2) = -0.4505429267992744
x_3 =  0.6859672323317240,	 f(x_3) =  0.0878395108141393
x_4 =  0.7363913805338105,	 f(x_4) =  0.0045056131852713
x_5 =  0.7391176625566099,	 f(x_5) = -0.0000544418881815
x_6 =  0.7390851138398410,	 f(x_6) =  0.0000000324267678
x_7 =  0.7390851332150215,	 f(x_7) =  0.0000000000002329
x_8 =  0.7390851332151607,	 f(x_8) =  0.0000000000000000



0.7390851332151607

In [9]:
# metoda siecznych może być wywołana bezpośrednio - wtedy podajemy przedział
secant_method(f,0,1, verbose=true)

Results of univariate zero finding:

* Converged to: 0.7390851332151607
* Algorithm Roots.Secant()
* iterations: 6
* function evaluations: 8
* stopped as |f(x_n)| ≤ max(δ, max(1,|x|)⋅ϵ) using δ = abstol, ϵ = reltol

Trace:
x_0 =  0.0000000000000000,	 f(x_0) =  1.0000000000000000
x_1 =  1.0000000000000000,	 f(x_1) = -0.4596976941318602
x_2 =  0.6850733573260451,	 f(x_2) =  0.0892992764818600
x_3 =  0.7362989976136540,	 f(x_3) =  0.0046600390381426
x_4 =  0.7391193619116293,	 f(x_4) = -0.0000572859911061
x_5 =  0.7390851121274639,	 f(x_5) =  0.0000000352926228
x_6 =  0.7390851332150012,	 f(x_6) =  0.0000000000002668
x_7 =  0.7390851332151607,	 f(x_7) =  0.0000000000000000



0.7390851332151607

Metody fzero dla wyzszych rzędów to wariacje metody Newtona, które nie korzystaja z pochodnej, ale ja przyblizają.


In [10]:
# np. metoda Steffensena przybliża pochodną poprzez  (f(x + f(x)) - f(x))/f(x) 
# aby ja wywołać podajemy punkt startowy oraz order 2
x = fzero(f, 0, order=2, verbose=true) 

Results of univariate zero finding:

* Converged to: 0.7390851332151607
* Algorithm Roots.Steffensen()
* iterations: 5
* function evaluations: 11
* stopped as |f(x_n)| ≤ max(δ, max(1,|x|)⋅ϵ) using δ = abstol, ϵ = reltol

Trace:
x_0 =  0.0000000000000000,	 f(x_0) =  1.0000000000000000
x_1 =  0.9999999925494194,	 f(x_1) = -0.4596976804118323
x_2 =  0.7503638670737971,	 f(x_2) = -0.0189230725330267
x_3 =  0.7391128908368132,	 f(x_3) = -0.0000464557742240
x_4 =  0.7390851333852108,	 f(x_4) = -0.0000000002845979
x_5 =  0.7390851332151607,	 f(x_5) =  0.0000000000000000



0.7390851332151607

In [18]:
# mozliwe sa jeszcze rzędy 5, 8 i 16
x = fzero(f, 0, order=16, verbose=true) 

Results of univariate zero finding:

* Converged to: 0.7390851332151607
* Algorithm Roots.Order16()
* iterations: 2
* function evaluations: 11
* stopped as |f(x_n)| ≤ max(δ, max(1,|x|)⋅ϵ) using δ = abstol, ϵ = reltol

Trace:
x_0 =  0.0000000000000000,	 f(x_0) =  1.0000000000000000
x_1 =  0.7401877925386848,	 f(x_1) = -0.0018458730685117
x_2 =  0.7390851332151607,	 f(x_2) =  0.0000000000000000



0.7390851332151607

Metoda Halleya używa pierwszej i drugiej pochodnej

In [12]:
halley(f, 2, verbose=true)

Results of univariate zero finding:

* Converged to: 0.7390851332151607
* Algorithm Roots.Halley()
* iterations: 4
* function evaluations: 13
* stopped as |f(x_n)| ≤ max(δ, max(1,|x|)⋅ϵ) using δ = abstol, ϵ = reltol

Trace:
x_0 =  2.0000000000000000,	 f(x_0) = -2.4161468365471426
x_1 =  0.8879042340553993,	 f(x_1) = -0.2568650304311213
x_2 =  0.7394368259674560,	 f(x_2) = -0.0005886429238380
x_3 =  0.7390851332201985,	 f(x_3) = -0.0000000000084315
x_4 =  0.7390851332151607,	 f(x_4) =  0.0000000000000000



0.7390851332151607

Można użyć funkcji fzero do znajdowania nieciagłości

In [13]:
plot(x -> 1/x)

In [14]:
fzero(x -> 1/x, -1, 1, verbose=true)

Results of univariate zero finding:

* Converged to: -5.0e-324
* Algorithm Roots.Bisection()
* iterations: 62
* function evaluations: 64
* stopped as x_n ≈ x_{n-1} using atol=xabstol, rtol=xreltol

Trace:
x_0 = -1.0000000000000000,	 f(x_0) = -1.0000000000000000
x_1 = -1.0000000000000000,	 f(x_1) = -1.0000000000000000
x_2 = -0.0000000000000000,	 f(x_2) = -8938538619961730903527447546336260136647857695517166799729872066605380201218388677218162180031619961113597284861729944421954505330253577338001054203117568.0000000000000000
x_3 = -0.0000000000000000,	 f(x_3) = -887153195600405056552521644282257721497433014862096317007019833469240250666595754544440453043013879108671543042926793316161496173994797360762233878874136368981907299234533748505074661636092656030310851438270325130299548808442281984.0000000000000000
x_4 = -0.0000000000000000,	 f(x_4) = -28175708327235479414441620361969415370007394080819352986837092317385965601051399236415193094256731898788353223581454110344870037303400383904263606

-5.0e-324

fzeros - szukanie więcej niż jednego pierwiastka. Wykorzystuje podział przedziału na mniejsze podprzedziały

In [15]:
fzeros(x ->(x-3)*x, -10, 10,verbose=true)

2-element Array{Float64,1}:
 0.0
 3.0

In [16]:
plot(x ->(x-3)*x,-1,4)

Więcej na https://github.com/JuliaMath/Roots.jl/blob/master/doc/roots.ipynb

### Zadanie:

Wybrać trzy metody poszukiwania pierwiastków: 

1. wykorzytującą przedział, 
+ wykorzystującą pochodną, 
+ wykorzystującą punkt startowy i przybliżenie pochodnej


1. Każdą z trzech wybranych metod przetestować (ilość iteracji, ilość wywołań funkcji) na sześciu wybranych  funkcjach ze zbioru http://people.sc.fsu.edu/~jburkardt/py_src/test_zero/test_zero.html . Wyniki przedstawić w formie tabelki. <b> Pamiętać o sprawdzeniu czy wynik jest poprawny poprzez obliczenie wartości funkcji dla znalezionego pierwiastka !</b>

+ Zademonstrować wybrany, ciekawy przykład trudnej funkcji z p.1 i działania metod na niej.

+ Dla każdej z wybranych metod zademonstrować i wyjaśnić po jednym  przykładzie, dla którego nie działają (można na podstawie p.1 lub wymyślić własny)